- name: Verifier SONAR_TOKEN
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: |
    if [ -z "$SONAR_TOKEN" ]; then
      echo "SONAR_TOKEN manquant dans GitHub Actions"
      exit 1
    else
      echo "SONAR_TOKEN charge correctement"
    fi

- name: Analyse SonarCloud
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: |
    ./mvnw sonar:sonar \
      -Dsonar.projectKey=Nirina2108_TP_4_auth_master_key \
      -Dsonar.organization=nirina2108 \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.token="$SONAR_TOKEN" \
      -Dsonar.qualitygate.wait=true \
      -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml